[package]
name = "amake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "1.0.18"
walkdir = "2.4.0"
zip = { version = "0.6.6", default-features = false , features = ["deflate"] }
