# -*- makefile-gmake -*-
# Build rules for internal libraries.
# Do not invoke this directly; these rules are used automatically when relevant.

ifndef VERBOSE # use "make VERBOSE=true" to show outputs
REDIR = >/dev/null 2>&1
REDSO = >/dev/null
endif

#EL = extlib/lib
#EI = extlib/include
#EB = extlib/bin
#ES = extlib/src

ROOT_DIR = $(shell pwd)

EXTERNAL_SOURCE = $(ROOT_DIR)/extlib/src

EXTERNAL_PREFIX = $(ROOT_DIR)/build/extlib
EXTERNAL_INSTALL_PREFIX = $(EXTERNAL_PREFIX)/install
EXTERNAL_INTERMEDIATE_PREFIX = $(EXTERNAL_PREFIX)/src

#OUTDIRS += $(EL)
#OUTDIRS += $(EI)
#OUTDIRS += $(EB)
#
#OUTDIRS := $(OUTDIRS)

#PKG_CONFIG_PATH := $(TOPSRC)/$(EL)/pkgconfig:$(PKG_CONFIG_PATH)
#export PKG_CONFIG_PATH

# NOTE: If you update one of these versions, you _MUST_ double check the file
# list (named <libname>_target below) used as output when building them.
SDL_VER      = SDL-1.2.15
SDLIMAGE_VER = SDL_image-1.2.12
ZLIB_VER     = zlib-1.2.13
PNG_VER      = libpng-1.6.39
JPEG_VER     = jpeg-9f
SDLMIXER_VER = SDL_mixer-1.2.12
OGG_VER      = libogg-1.3.5
VORB_VER     = libvorbis-1.3.7
SMPEG_VER    = smpeg
BZIP_VER     = bzip2-1.0.8
FREETYPE_VER = freetype-2.13.0
SDLT_VER     = SDL_ttf-2.0.11

# ZLIB_SRC     = $(EXTERNAL_SOURCE)/$(ZLIB_SRC)
# PNG_SRC      = $(EXTERNAL_SOURCE)/$(PNG_SRC)
# JPEG_SRC     = $(EXTERNAL_SOURCE)/$(JPEG_SRC)
# SMPEG_SRC    = $(EXTERNAL_SOURCE)/$(SMPEG_SRC)
# BZIP_SRC     = $(EXTERNAL_SOURCE)/$(BZIP_SRC)
# FREETYPE_SRC = $(EXTERNAL_SOURCE)/$(FREETYPE_SRC)
# OGG_SRC      = $(EXTERNAL_SOURCE)/$(OGG_SRC)
# VORB_SRC     = $(EXTERNAL_SOURCE)/$(VORB_SRC)
# SDL_SRC      = $(EXTERNAL_SOURCE)/$(SDL_SRC)
# SDLT_SRC     = $(EXTERNAL_SOURCE)/$(SDLT_SRC)
# SDLMIXER_SRC = $(EXTERNAL_SOURCE)/$(SDLMIXER_SRC)
# SDLIMAGE_SRC = $(EXTERNAL_SOURCE)/$(SDLIMAGE_SRC)

# SDL_INTERMEDIATE_SRC      = $(INTERMEDIATE_PREFIX)/$(SDL_SRC)
# SDLIMAGE_INTERMEDIATE_SRC = $(INTERMEDIATE_PREFIX)/$(SDLIMAGE_SRC)
# ZLIB_INTERMEDIATE_SRC     = $(INTERMEDIATE_PREFIX)/$(ZLIB_SRC)
# PNG_INTERMEDIATE_SRC      = $(INTERMEDIATE_PREFIX)/$(PNG_SRC)
# JPEG_INTERMEDIATE_SRC     = $(INTERMEDIATE_PREFIX)/$(JPEG_SRC)
# SDLMIXER_INTERMEDIATE_SRC = $(INTERMEDIATE_PREFIX)/$(SDLMIXER_SRC)
# OGG_INTERMEDIATE_SRC      = $(INTERMEDIATE_PREFIX)/$(OGG_SRC)
# VORB_INTERMEDIATE_SRC     = $(INTERMEDIATE_PREFIX)/$(VORB_SRC)
# SMPEG_INTERMEDIATE_SRC    = $(INTERMEDIATE_PREFIX)/$(SMPEG_SRC)
# BZIP_INTERMEDIATE_SRC     = $(INTERMEDIATE_PREFIX)/$(BZIP_SRC)
# FREETYPE_INTERMEDIATE_SRC = $(INTERMEDIATE_PREFIX)/$(FREETYPE_SRC)
# SDLT_INTERMEDIATE_SRC     = $(INTERMEDIATE_PREFIX)/$(SDLT_SRC)



##------------------------------------------------------------------------------

##-- zlib ----------------------------------------------------------------------
# zlib_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(ZLIB_VER)" -type f )
# zlib_target = $(addprefix $(EXTERNAL_INSTALL_PREFIX)/, include/zconf.h include/zlib.h lib/libz.a lib/pkgconfig/zlib.pc share/man/man3/zlib.3)
# $(zlib_target): $(zlib_input_files)
# 	@echo "Building $(ZLIB_VER)"  && \
# 	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(ZLIB_VER)
# 	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX) && \
# 	cp -r $(EXTERNAL_SOURCE)/$(ZLIB_VER) $(EXTERNAL_INTERMEDIATE_PREFIX) && \
# 	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(ZLIB_VER)  && \
# 	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --static  && \
# 	$(MAKE) -j  && \
# 	$(MAKE) install
	
##-- ogg -----------------------------------------------------------------------
libogg_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(OGG_VER)" -type f )
libogg_target = $(addprefix $(EXTERNAL_INSTALL_PREFIX)/, include/ogg/config_types.h include/ogg/ogg.h include/ogg/os_types.h lib/libogg.a lib/libogg.la lib/pkgconfig/ogg.pc share/aclocal/ogg.m4)
$(libogg_target): $(libogg_input_files)
	@echo "Building $(OGG_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(OGG_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	mkdir -p $(EXTERNAL_INSTALL_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(OGG_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(OGG_VER) && \
	autoreconf -ivf && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --disable-shared --disable-dependency-trackin && \
	$(MAKE) -j  && \
	$(MAKE) install
	
##-- vorbis --------------------------------------------------------------------
#libvorbis_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(OGG_VER)" -type f )
#libvorbis_target = $(addprefix $(EXTERNAL_INSTALL_PREFIX)/, include/zconf.h include/zlib.h lib/libz.a lib/pkgconfig/zlib.pc share/man/man3/zlib.3)
#$(libvorbis_target): $(libvorbis_input_files)
#	@echo "Building $(OGG_VER)"  && \
#	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(OGG_VER)
#	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX) && \
#	cp -r $(EXTERNAL_SOURCE)/$(OGG_VER) $(EXTERNAL_INTERMEDIATE_PREFIX) && \
#	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(OGG_VER)  && \
#	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --static  && \
#	$(MAKE) -j  && \
#	$(MAKE) install

##-- test ----------------------------------------------------------------------
#testing: $(zlib_target) #$(libogg_target) 
testing: $(libogg_target) 
	echo "Weee"

#CLEAN_TARGETS=clean_sdl clean_sdl_image clean_sdl_mixer clean_bzip2   \
#              clean_smpeg clean_freetype clean_sdl_ttf
#DISTCLEAN_TARGETS=dclean_sdl dclean_sdl_image dclean_sdl_mixer        \
#                  dclean_smpeg dclean_freetype dclean_sdl_ttf
#
##-- SDL -----------------------------------------------------------------------
#
#.PHONY: clean_sdl dclean_sdl
#internal_sdl = $(EB)/sdl-config
#clean_sdl:
#	@if [ -f $(SDLSRC)/Makefile ]; then $(MAKE) -C $(SDLSRC) uninstall; fi
#	@if [ -f $(SDLSRC)/Makefile ]; then $(MAKE) -C $(SDLSRC) clean; fi
#dclean_sdl: clean_sdl
#	@if [ -f $(SDLSRC)/Makefile ]; then $(MAKE) -C $(SDLSRC) distclean; fi
#
#$(SDLSRC)/Makefile: $(if $(INTERNAL_LIBPNG),$(EL)/libpng$(LIBSUFFIX))
#	@echo Configuring internal SDL...
#	@cd $(SDLSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" $(SDLOTHERCONFIG) \
#	    $(addprefix --disable-,shared joystick nas $(addprefix video-,fbcon directfb svga vgl wscons opengl)) \
#	    $(REDIR)
#	@cp $(ES)/required/libtool $(SDLSRC)/libtool # This line fixes a libtool issue by just using the copy of libtool from the old build of ONSCripter-EN. It's not pretty, but it works. -Galladite, 2022-2-9
#
#$(EB)/sdl-config: $(SDLSRC)/Makefile | $(EB)
#	@echo Building internal SDL...
#	@$(MAKE) -C $(SDLSRC) $(REDSO)
#	@$(MAKE) -C $(SDLSRC) install $(REDSO)
#	@if [ -n "$(WIN32)" ]; then \
#	    mv $@ $@.tmp; \
#	    sed -e 's/\(-lmingw32 -lSDLmain.*\)$$/\1 -lwinmm/' $@.tmp > $@; \
#	    rm $@.tmp; \
#	fi # Fix for annoying Windows breakage
#	@cp -r $(EI)/SDL/* $(EI)
#
##-- SDL_image -----------------------------------------------------------------
#
#.PHONY: clean_sdl_image dclean_sdl_image
#internal_sdl_image = $(EL)/libSDL_image$(LIBSUFFIX)
#clean_sdl_image:
#	@-if [ -f $(SDLISRC)/Makefile ]; then $(MAKE) -C $(SDLISRC) uninstall; fi
#	@-if [ -f $(SDLISRC)/Makefile ]; then $(MAKE) -C $(SDLISRC) clean; fi
#	@-if [ -f $(EL)/libz$(LIBSUFFIX) ]; then $(MAKE) -C $(ZSRC) uninstall prefix="$(INSTALL_PREFIX)"; fi
#	@-if [ -f $(ZSRC)/libz$(LIBSUFFIX) ]; then $(MAKE) -C $(ZSRC) clean; fi
#	@-if [ -f $(PNGSRC)/Makefile ]; then $(MAKE) -C $(PNGSRC) uninstall; fi
#	@-if [ -f $(PNGSRC)/Makefile ]; then $(MAKE) -C $(PNGSRC) clean; fi
#	@-if [ -f $(JPEGSRC)/Makefile ]; then \
#	    rm -f $(EL)/libjpeg$(LIBSUFFIX) $(addprefix $(EI)/,jconfig.h jpeglib.h jmorecfg.h jerror.h); \
#	    $(MAKE) -C $(JPEGSRC) clean; \
#	fi
#dclean_sdl_image:
#	@-if [ -f $(SDLISRC)/Makefile ]; then $(MAKE) -C $(SDLISRC) distclean; fi
#	@-if [ -f $(PNGSRC)/Makefile ]; then $(MAKE) -C $(PNGSRC) distclean; fi
#	@-if [ -f $(JPEGSRC)/Makefile ]; then $(MAKE) -C $(JPEGSRC) distclean; fi
#
#$(SDLISRC)/Makefile: $(if $(INTERNAL_SDL),$(EB)/sdl-config) \
#                     $(if $(INTERNAL_LIBPNG),$(EL)/libpng$(LIBSUFFIX)) \
#                     $(if $(INTERNAL_LIBJPEG),$(EL)/libjpeg$(LIBSUFFIX))
#	@echo Configuring internal SDL_image...
#	@cd $(SDLISRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" $(OTHERCONFIG) \
#	    $(addprefix --disable-,shared lbm pcx pnm tga xcf xv tif \
#	    	                   $(if $(INTERNAL_LIBPNG),png-shared) \
#                                   $(if $(INTERNAL_LIBJPEG),jpg-shared)) \
#            CFLAGS="$(CFLAGS) -Wno-error=incompatible-pointer-types" \
#	    $(REDIR)
#	@if grep -q 'PNG image loading disabled' $(SDLISRC)/config.log; then \
#	    echo "PNG error - check $(SDLISRC)/config.log for details"; \
#	    rm Makefile; \
#	    exit 1; \
#	fi
#
#$(EL)/libSDL_image$(LIBSUFFIX): $(SDLISRC)/Makefile | $(EL) $(EI)
#	@echo Building internal SDL_image...
#	@$(MAKE) -C $(SDLISRC) $(REDSO)
#	@$(MAKE) -C $(SDLISRC) install $(REDSO)
#	@cp -r $(EI)/SDL/* $(EI)
#
## First build libz, libpng, and libjpeg, if required.
#
#internal_png = $(EL)/libpng$(LIBSUFFIX)
#internal_jpeg = $(EL)/libjpeg$(LIBSUFFIX)
#
#$(PNGSRC)/Makefile: $(EL)/libz$(LIBSUFFIX)
#	@echo Configuring internal libpng...
#	@cd $(PNGSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" --disable-shared --disable-dependency-tracking --with-zlib-prefix="$(INSTALL_PREFIX)" $(OTHERCONFIG) $(REDIR)
#
#$(EL)/libpng$(LIBSUFFIX): $(PNGSRC)/Makefile | $(EL)
#	@echo Building internal libpng...
#	@$(MAKE) -C $(PNGSRC) $(REDSO)
#	@$(MAKE) -C $(PNGSRC) install $(REDSO)
#	@sed -i '/^Requires.*:/s/ zlib//' $(EL)/pkgconfig/libpng*.pc
#
#$(EL)/libz$(LIBSUFFIX): | $(EL)
#	@echo Building internal zlib...
#	@cd $(ZSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" --static $(OTHERCONFIG) $(REDIR)
#	@$(MAKE) -C $(ZSRC) install $(REDSO)
#
#$(JPEGSRC)/Makefile:
#	@echo Configuring internal libjpeg...
#	@sed -i -e '/^bin_PROGRAMS/s/bin_/EXTRA_/' -e '/^man_MANS/s/=.*$$/=/' $(JPEGSRC)/Makefile.am
#	@cd $(JPEGSRC) && \
#	autoreconf -fi && \
#	./configure --prefix="$(INSTALL_PREFIX)" --disable-shared --enable-static $(OTHERCONFIG) $(REDIR)
#
#$(EL)/libjpeg$(LIBSUFFIX): $(JPEGSRC)/Makefile | $(EL)
#	@echo Building internal libjpeg...
#	@$(MAKE) -C $(JPEGSRC) install $(REDSO)
#
##-- SDL_mixer -----------------------------------------------------------------
#
#OGGLIBS = $(EL)/libogg$(LIBSUFFIX) $(EL)/libvorbis$(LIBSUFFIX) $(EL)/libvorbisfile$(LIBSUFFIX)
#
#.PHONY: clean_sdl_mixer dclean_sdl_mixer
#internal_sdl_mixer = $(EL)/libSDL_mixer$(LIBSUFFIX)
#clean_sdl_mixer:
#	@if [ -f $(SDLMSRC)/Makefile ]; then $(MAKE) -C $(SDLMSRC) uninstall; fi
#	@if [ -f $(VORBSRC)/Makefile ]; then $(MAKE) -C $(VORBSRC) uninstall; fi
#	@if [ -f $(OGGSRC)/Makefile  ]; then $(MAKE) -C $(OGGSRC)  uninstall; fi
#	@if [ -f $(SDLMSRC)/Makefile ]; then $(MAKE) -C $(SDLMSRC) clean; fi
#	@if [ -f $(VORBSRC)/Makefile ]; then $(MAKE) -C $(VORBSRC) clean; fi
#	@if [ -f $(OGGSRC)/Makefile  ]; then $(MAKE) -C $(OGGSRC)  clean; fi
#dclean_sdl_mixer:
#	@if [ -f $(SDLMSRC)/Makefile ]; then $(MAKE) -C $(SDLMSRC) distclean; fi
#	@if [ -f $(VORBSRC)/Makefile ]; then $(MAKE) -C $(VORBSRC) distclean; fi
#	@if [ -f $(OGGSRC)/Makefile  ]; then $(MAKE) -C $(OGGSRC)  distclean; fi
#
#$(SDLMSRC)/Makefile: $(if $(INTERNAL_SDL),$(EB)/sdl-config) \
#                     $(if $(INTERNAL_SMPEG),$(EB)/smpeg-config) \
#                     $(if $(INTERNAL_OGGLIBS),$(OGGLIBS))
#	@echo Configuring internal SDL_mixer...
#	@cd $(SDLMSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" $(SDL_MIXER_FLAGS) $(OTHERCONFIG) \
#	    $(addprefix --disable-,shared $(addprefix music-,cmd timidity-midi)) \
#	    CFLAGS="$(CFLAGS) -Wno-error=implicit-function-declaration" \
#	    $(REDIR)
#
#$(EL)/libSDL_mixer$(LIBSUFFIX): $(SDLMSRC)/Makefile | $(EL)
#	@echo Building internal SDL_mixer...
#	@$(MAKE) -C $(SDLMSRC) $(REDSO)
#	@$(MAKE) -C $(SDLMSRC) install $(REDSO)
#	@-if [ -f $(EI)/SDL_mixer.h ]; then rm $(EI)/SDL_mixer.h; fi
#	@cp -r $(EI)/SDL/* $(EI)
#
## First build Ogg libs, if required.
#
#internal_ogglibs = $(OGGLIBS)
#
#$(OGGSRC)/Makefile:
#	@echo Configuring internal libogg...
#	@cd $(OGGSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" --disable-shared --disable-dependency-tracking $(OTHERCONFIG) $(REDIR)
#
#$(EL)/libogg$(LIBSUFFIX): $(OGGSRC)/Makefile | $(EL)
#	@echo Building internal libogg...
#	@$(MAKE) -C $(OGGSRC) $(REDSO)
#	@$(MAKE) -C $(OGGSRC) install $(REDSO)
#
#$(VORBSRC)/Makefile: $(EL)/libogg$(LIBSUFFIX)
#	@echo Configuring internal libvorbis...
#	@cd $(VORBSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" $(addprefix --disable-,shared dependency-tracking docs) $(OTHERCONFIG) $(REDIR)
#
#$(EL)/libvorbisfile$(LIBSUFFIX): $(EL)/libvorbis$(LIBSUFFIX)
#$(EL)/libvorbis$(LIBSUFFIX): $(VORBSRC)/Makefile | $(EL)
#	@echo Building internal libvorbis...
#	@$(MAKE) -C $(VORBSRC) $(REDSO)
#	@$(MAKE) -C $(VORBSRC) install $(REDSO)
#
##-- SMPEG ---------------------------------------------------------------------
#
#.PHONY: clean_smpeg dclean_smpeg
#internal_smpeg = $(EB)/smpeg-config
#clean_smpeg:
#	@-if [ -f $(SMPGSRC)/Makefile ]; then $(MAKE) -C $(SMPGSRC) uninstall; fi
#	@-if [ -f $(SMPGSRC)/Makefile ]; then $(MAKE) -C $(SMPGSRC) clean; fi
#	@-if [ -f $(EI)/smpeg.h ]; then rm $(EI)/MPEG* $(EI)/smpeg.h; fi
#dclean_smpeg: clean_smpeg
#	@-if [ -f $(SMPGSRC)/Makefile ]; then $(MAKE) -C $(SMPGSRC) distclean; fi
#
#ifdef DEBUG
#	SMPEG_DEBUG=
#else
#	SMPEG_DEBUG=debug
#endif
#
#$(SMPGSRC)/Makefile: $(if $(INTERNAL_SDL),$(EB)/sdl-config)
#	@echo Configuring internal smpeg...
#	@cd $(SMPGSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" $(OTHERCONFIG) \
#	    $(addprefix --disable-,shared gtk-player opengl-player $(SMPEG_DEBUG)) \
#	    $(REDIR)
#
#$(EB)/smpeg-config: $(SMPGSRC)/Makefile | $(EB)
#	@echo Building internal smpeg...
#	@$(MAKE) -C $(SMPGSRC) $(REDSO)
#	@$(MAKE) -C $(SMPGSRC) prefix="$(INSTALL_PREFIX)" install $(REDSO)
#	@cp -r $(EI)/smpeg/* $(EI)
#
##-- Freetype ------------------------------------------------------------------
#
#FTCONFIGURE = $(FTSRC)/builds/unix/config.status
#
#.PHONY: clean_freetype dclean_freetype
#internal_freetype = $(EB)/freetype-config
#clean_freetype:
#	@-if [ -f $(FTCONFIGURE) ]; then $(MAKE) -C $(FTSRC) uninstall; fi
#	@-if [ -f $(FTCONFIGURE) ]; then $(MAKE) -C $(FTSRC) clean; fi
#dclean_freetype:
#	@-if [ -f $(FTCONFIGURE) ]; then $(MAKE) -C $(FTSRC) distclean; fi
#
#$(FTCONFIGURE): $(if $(INTERNAL_LIBPNG),$(EL)/libz$(LIBSUFFIX))
#	@echo Configuring internal Freetype...
#	@cd $(FTSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" --disable-shared --without-harfbuzz --without-brotli $(OTHERCONFIG) $(REDIR)
#
#$(EB)/freetype-config: $(FTCONFIGURE) | $(EB)
#	@echo Building internal Freetype...
#	@$(MAKE) -C $(FTSRC) $(REDSO)
#	@$(MAKE) -C $(FTSRC) install $(REDSO)
#	@-if [ -h $(EI)/freetype ]; then rm -r $(EI)/freetype; fi
#	@-if [ -f $(EI)/ft2config.h ]; then rm $(EI)/ft2config.h; fi
#	@cp -r $(EI)/freetype2/* $(EI)
#	@touch $@
#
##-- SDL_ttf -------------------------------------------------------------------
#
#.PHONY: clean_sdl_ttf dclean_sdl_ttf
#internal_sdl_ttf = $(EL)/libSDL_ttf$(LIBSUFFIX)
#clean_sdl_ttf:
#	@if [ -f $(SDLTSRC)/Makefile ]; then $(MAKE) -C $(SDLTSRC) uninstall; fi
#	@if [ -f $(SDLTSRC)/Makefile ]; then $(MAKE) -C $(SDLTSRC) clean; fi
#dclean_sdl_ttf: clean_sdl_ttf
#	@if [ -f $(SDLTSRC)/Makefile ]; then $(MAKE) -C $(SDLTSRC) distclean; fi
#
#$(SDLTSRC)/Makefile: $(if $(INTERNAL_SDL),$(EB)/sdl-config) $(if $(INTERNAL_FREETYPE),$(EB)/freetype-config)
#	@echo Configuring internal SDL_ttf...
#	@cd $(SDLTSRC) && \
#	./configure --prefix="$(INSTALL_PREFIX)" --disable-shared $(OTHERCONFIG) $(REDIR)
#
#$(EL)/libSDL_ttf$(LIBSUFFIX): $(SDLTSRC)/Makefile | $(EL)
#	@echo Building internal SDL_ttf...
#	@$(MAKE) -C $(SDLTSRC) $(REDSO)
#	@$(MAKE) -C $(SDLTSRC) install $(REDSO)
#	@cp -r $(EI)/SDL/* $(EI)
#
##-- libbzip2 ------------------------------------------------------------------
#
#BZOBJS = blocksort huffman crctable randtable compress decompress bzlib
#
#.PHONY: clean_bzip2
#internal_bzip2 = $(EL)/libbz2$(LIBSUFFIX) $(EI)/bzlib.h
#clean_bzip2:
#	rm -f $(EL)/libbz2$(LIBSUFFIX) $(EI)/bzlib.h $(BZSRC)/*$(OBJSUFFIX)
#
#$(EL)/libbz2$(LIBSUFFIX): $(foreach fn,$(BZOBJS),$(BZSRC)/$(fn)$(OBJSUFFIX)) | $(EL)
#	rm -f $@
#	$(AR) cq $@ $^
#	@if [ -f "$(RANLIB)" -o -f /usr/bin/ranlib -o \
#	    -f /bin/ranlib -o -f /usr/ccs/bin/ranlib ]; then \
#	    $(if $(RANLIB),$(RANLIB),ranlib) $@ ; \
#	fi
#
#$(EI)/bzlib.h: $(BZSRC)/bzlib.h | $(EI)
#	cp $< $@
#
#$(sort $(OUTDIRS)):
#	mkdir -p $@
#