# -*- makefile-gmake -*-
#
# Makefile.onscripter - General makefile rules for ONScripter
#

TARGET ?= onscripter-en

TDIR = tools/
TOOLBINS = $(OBJDIR)sardec$(EXESUFFIX) $(OBJDIR)nsadec$(EXESUFFIX)	\
        $(OBJDIR)ns2dec$(EXESUFFIX) $(OBJDIR)nscdec$(EXESUFFIX)	\
        $(OBJDIR)sarconv$(EXESUFFIX) $(OBJDIR)nsaconv$(EXESUFFIX)	\
        $(OBJDIR)ns2conv$(EXESUFFIX) $(OBJDIR)batchconv$(EXESUFFIX)	\
        $(OBJDIR)sarmake$(EXESUFFIX) $(OBJDIR)nsamake$(EXESUFFIX)	\
        $(OBJDIR)ns2make$(EXESUFFIX) $(OBJDIR)nscmake$(EXESUFFIX)	\
        $(OBJDIR)nbzdec$(EXESUFFIX)
TOOLS = $(TOOLBINS:%=$(TDIR)%)
TOOL_INCS = -I`pwd` -I$(INSTALLDIR)/include $(TOOL_EXTRA_INCS)
TOOL_DEFS = $(DEFS) -DTOOLS_BUILD

GUI_OBJS = \
	$(OBJDIR)AnimationInfo$(OBJSUFFIX) \
	$(OBJDIR)FontInfo$(OBJSUFFIX) \
	$(OBJDIR)DirtyRect$(OBJSUFFIX) \
	$(OBJDIR)graphics_routines$(OBJSUFFIX) \
	$(OBJDIR)ONScripterReporter$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_command$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_text$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_effect$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_effect_breakup$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_effect_cascade$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_effect_trig$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_event$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_rmenu$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_animation$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_sound$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_file$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_file2$(OBJSUFFIX) \
	$(OBJDIR)ONScripterLabel_image$(OBJSUFFIX) \
	$(OBJDIR)resize_image$(OBJSUFFIX) \
	$(OBJDIR)ShiftJISData$(OBJSUFFIX)
DECODER_OBJS = $(OBJDIR)DirectReader$(OBJSUFFIX) $(OBJDIR)SarReader$(OBJSUFFIX)	\
               $(OBJDIR)NsaReader$(OBJSUFFIX)
ONSCRIPTER_OBJS = $(OBJDIR)onscripter$(OBJSUFFIX) $(DECODER_OBJS)		\
                  $(OBJDIR)ScriptHandler$(OBJSUFFIX) $(OBJDIR)ScriptParser$(OBJSUFFIX)	\
                  $(OBJDIR)ScriptParser_command$(OBJSUFFIX) $(GUI_OBJS)		\
                  $(OBJDIR)sjis2utf16$(OBJSUFFIX) $(EXT_OBJS) $(OTHER_OBJS)	\
                  $(OBJDIR)DirPaths$(OBJSUFFIX) $(OBJDIR)Layer$(OBJSUFFIX)		\
                  $(OBJDIR)Encoding$(OBJSUFFIX)
SARDEC_OBJS   = $(TOBJDIR)sardec$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)DirPaths$(OBJSUFFIX)        \
                $(TOBJDIR)sjis2utf16$(OBJSUFFIX)
SARMAKE_OBJS  = $(TOBJDIR)sarmake$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)DirPaths$(OBJSUFFIX)        \
                $(TOBJDIR)sjis2utf16$(OBJSUFFIX)
SARCONV_OBJS  = $(TOBJDIR)sarconv$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)DirPaths$(OBJSUFFIX)	\
                $(TOBJDIR)resize_image$(OBJSUFFIX) $(TOBJDIR)conv_shared$(OBJSUFFIX)  \
                $(TOBJDIR)conv_shared_jpeg$(OBJSUFFIX) $(TOBJDIR)sjis2utf16$(OBJSUFFIX) \
				$(TOBJDIR)conv_shared_png$(OBJSUFFIX)
NSADEC_OBJS   = $(TOBJDIR)nsadec$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)NsaReader$(OBJSUFFIX)	\
                $(TOBJDIR)DirPaths$(OBJSUFFIX) $(TOBJDIR)sjis2utf16$(OBJSUFFIX)
NSACONV_OBJS  = $(TOBJDIR)nsaconv$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)NsaReader$(OBJSUFFIX)	\
                $(TOBJDIR)DirPaths$(OBJSUFFIX) $(TOBJDIR)resize_image$(OBJSUFFIX)	\
                $(TOBJDIR)conv_shared$(OBJSUFFIX) $(TOBJDIR)sjis2utf16$(OBJSUFFIX) \
                $(TOBJDIR)conv_shared_jpeg$(OBJSUFFIX) $(TOBJDIR)conv_shared_png$(OBJSUFFIX)
NSAMAKE_OBJS  = $(TOBJDIR)nsamake$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)NsaReader$(OBJSUFFIX)	\
                $(TOBJDIR)DirPaths$(OBJSUFFIX) $(TOBJDIR)sjis2utf16$(OBJSUFFIX)
NS2DEC_OBJS   = $(TOBJDIR)ns2dec$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)NsaReader$(OBJSUFFIX)	\
                $(TOBJDIR)DirPaths$(OBJSUFFIX) $(TOBJDIR)sjis2utf16$(OBJSUFFIX)
NS2CONV_OBJS  = $(TOBJDIR)ns2conv$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)NsaReader$(OBJSUFFIX)	\
                $(TOBJDIR)DirPaths$(OBJSUFFIX) $(TOBJDIR)resize_image$(OBJSUFFIX)	\
                $(TOBJDIR)conv_shared$(OBJSUFFIX) $(TOBJDIR)sjis2utf16$(OBJSUFFIX) \
                $(TOBJDIR)conv_shared_jpeg$(OBJSUFFIX) $(TOBJDIR)conv_shared_png$(OBJSUFFIX)
NS2MAKE_OBJS  = $(TOBJDIR)ns2make$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)NsaReader$(OBJSUFFIX)	\
                $(TOBJDIR)DirPaths$(OBJSUFFIX) $(TOBJDIR)sjis2utf16$(OBJSUFFIX)
BATCONV_OBJS  = $(TOBJDIR)batchconv$(OBJSUFFIX) $(TOBJDIR)resize_image$(OBJSUFFIX)	\
                $(TOBJDIR)conv_shared$(OBJSUFFIX) $(TOBJDIR)conv_shared_jpeg$(OBJSUFFIX) \
				$(TOBJDIR)conv_shared_png$(OBJSUFFIX)
NBZDEC_OBJS   = $(TOBJDIR)nbzdec$(OBJSUFFIX) $(TOBJDIR)DirectReader$(OBJSUFFIX)	\
                $(TOBJDIR)SarReader$(OBJSUFFIX) $(TOBJDIR)DirPaths$(OBJSUFFIX)	\
                $(TOBJDIR)sjis2utf16$(OBJSUFFIX)
READER_HEADER = BaseReader.h DirectReader.h DirPaths.h
PARSER_HEADER = $(EXTRADEPS) SarReader.h NsaReader.h DirectReader.h	\
                $(READER_HEADER) ScriptHandler.h ScriptParser.h $(RC_HDRS)	\
                AnimationInfo.h FontInfo.h DirtyRect.h Layer.h LUAHandler.h
ONSCRIPTER_HEADER = ONScripterLabel.h $(PARSER_HEADER)

ALL: $(TARGET)$(EXESUFFIX) tools


$(TARGET)$(EXESUFFIX): export PKG_CONFIG_PATH=$(TOPSRC)/build/extlib/install/lib/pkgconfig
$(TARGET)$(EXESUFFIX): $(ONSCRIPTER_OBJS) $(INTERNALLY_BUILT_LIBS)
	$(CXX) -o $@ $(SANFLAGS) $(LDFLAGS) $(ONSCRIPTER_OBJS) $(LIBS)

$(ONSCRIPTER_OBJS): $(EXTRADEPS) $(INTERNALLY_BUILT_LIBS)

tools: $(TOOL_EXTRADEPS) $(TOOLS)

$(TOOLS): $(EXTRADEPS)

$(TDIR)sardec$(EXESUFFIX): $(SARDEC_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(SARDEC_OBJS) $(TOOL_LIBS)

$(TDIR)sarconv$(EXESUFFIX): $(SARCONV_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(SARCONV_OBJS) $(TOOL_LIBS)

$(TDIR)sarmake$(EXESUFFIX): $(SARMAKE_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(SARMAKE_OBJS) $(TOOL_LIBS)

$(TDIR)nsadec$(EXESUFFIX): $(NSADEC_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(NSADEC_OBJS) $(TOOL_LIBS)

$(TDIR)nsaconv$(EXESUFFIX): $(NSACONV_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(NSACONV_OBJS) $(TOOL_LIBS)

$(TDIR)nsamake$(EXESUFFIX): $(NSAMAKE_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(NSAMAKE_OBJS) $(TOOL_LIBS)

$(TDIR)ns2dec$(EXESUFFIX): $(NS2DEC_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(NS2DEC_OBJS) $(TOOL_LIBS)

$(TDIR)ns2conv$(EXESUFFIX): $(NS2CONV_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(NS2CONV_OBJS) $(TOOL_LIBS)

$(TDIR)ns2make$(EXESUFFIX): $(NS2MAKE_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(NS2MAKE_OBJS) $(TOOL_LIBS)

$(TDIR)batchconv$(EXESUFFIX): $(BATCONV_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(BATCONV_OBJS) $(TOOL_LIBS)

$(TDIR)nscdec$(EXESUFFIX): $(TDIR)nscdec$(OBJSUFFIX)
	$(CXX) -o $@ $(LDFLAGS) $< $(TOOL_LIBS)

$(TDIR)nscmake$(EXESUFFIX): $(TDIR)nscmake$(OBJSUFFIX)
	$(CXX) -o $@ $(LDFLAGS) $< $(TOOL_LIBS)

$(TDIR)nbzdec$(EXESUFFIX): $(NBZDEC_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(NBZDEC_OBJS) $(TOOL_LIBS)

CLEANUP += $(ONSCRIPTER_OBJS:.o=.d)

pclean:
	-$(RM) *$(OBJSUFFIX) $(CLEANUP) $(RCCLEAN)

pdistclean: pclean ptoolsdistclean
	-$(RM) $(TARGET_EXE)$(EXESUFFIX) onscripter-en$(EXESUFFIX)

ptoolsclean: $(TOOL_EXTRA_CLEAN)
	-$(RM) $(TDIR)*$(OBJSUFFIX)

ptoolsdistclean: ptoolsclean
	-$(RM) $(TOOLS)


$(TOBJDIR)sardec$(OBJSUFFIX): $(TDIR)arcdec.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DSAR $<

$(TOBJDIR)nsadec$(OBJSUFFIX): $(TDIR)arcdec.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DNSA $<

$(TOBJDIR)ns2dec$(OBJSUFFIX): $(TDIR)arcdec.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DNS2 $<

$(TOBJDIR)sarconv$(OBJSUFFIX): $(TDIR)arcconv.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DSAR $<

$(TOBJDIR)nsaconv$(OBJSUFFIX): $(TDIR)arcconv.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DNSA $<

$(TOBJDIR)ns2conv$(OBJSUFFIX): $(TDIR)arcconv.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DNS2 $<

$(TOBJDIR)sarmake$(OBJSUFFIX): $(TDIR)arcmake.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DSAR $<

$(TOBJDIR)nsamake$(OBJSUFFIX): $(TDIR)arcmake.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DNSA $<

$(TOBJDIR)ns2make$(OBJSUFFIX): $(TDIR)arcmake.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) -DNS2 $<

$(TOBJDIR)%$(OBJSUFFIX): $(TDIR)%.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) $<

$(TOBJDIR)%Reader$(OBJSUFFIX): %Reader.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) $<

$(TOBJDIR)DirPaths$(OBJSUFFIX): DirPaths.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) $<

$(TOBJDIR)resize_image$(OBJSUFFIX): resize_image.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) $<

$(TOBJDIR)sjis2utf16$(OBJSUFFIX): sjis2utf16.cpp
	@mkdir -p $(TOBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(TOOL_INCS) $(TOOL_DEFS) $<

$(OBJDIR)%$(OBJSUFFIX): %.cpp $(INTERNALLY_BUILT_LIBS)
	@mkdir -p $(OBJDIR)
	$(CXX) -c -o $@ $(CXXSTD) $(OSCFLAGS) $(INCS) $(DEPFLAGS) $(DEFS) $<

$(TDIR)sardec$(OBJSUFFIX): $(READER_HEADER) SarReader.h
$(TDIR)sarconv$(OBJSUFFIX): $(READER_HEADER) SarReader.h
$(TDIR)sarmake$(OBJSUFFIX): $(READER_HEADER) SarReader.h
$(TDIR)nsadec$(OBJSUFFIX): $(READER_HEADER) SarReader.h NsaReader.h
$(TDIR)nsaconv$(OBJSUFFIX): $(READER_HEADER) SarReader.h NsaReader.h
$(TDIR)nsamake$(OBJSUFFIX): $(READER_HEADER) SarReader.h NsaReader.h
$(TDIR)ns2dec$(OBJSUFFIX): $(READER_HEADER) SarReader.h NsaReader.h
$(TDIR)ns2conv$(OBJSUFFIX): $(READER_HEADER) SarReader.h NsaReader.h
$(TDIR)ns2make$(OBJSUFFIX): $(READER_HEADER) SarReader.h NsaReader.h
$(TDIR)nbzdec$(OBJSUFFIX): $(READER_HEADER) SarReader.h
$(TDIR)conv_shared$(OBJSUFFIX): $(TDIR)conv_shared.h resize_image.h
$(TDIR)conv_shared_jpeg$(OBJSUFFIX): $(TDIR)conv_shared.h resize_image.h
$(TDIR)conv_shared_png$(OBJSUFFIX): $(TDIR)conv_shared.h resize_image.h
$(TDIR)SarReader$(OBJSUFFIX):    $(READER_HEADER) SarReader.h 
$(TDIR)NsaReader$(OBJSUFFIX):    $(READER_HEADER) SarReader.h NsaReader.h 
$(TDIR)DirectReader$(OBJSUFFIX): $(READER_HEADER) DirectReader.h
$(TDIR)DirPaths$(OBJSUFFIX): DirPaths.h 
$(TDIR)resize_image$(OBJSUFFIX): resize_image.h

-include $(wildcard $(ONSCRIPTER_OBJS:.o=.d))
