# -*- makefile-gmake -*-
# Build rules for internal libraries.
# Do not invoke this directly; these rules are used automatically when relevant.

ifndef VERBOSE # use "make VERBOSE=true" to show outputs
REDIR = >/dev/null 2>&1
REDSO = >/dev/null
endif


# TODO: Move these variables to be in the configure/makefile.
ROOT_DIR = $(shell pwd)
EXTERNAL_SOURCE = $(ROOT_DIR)/extlib/src
EXTERNAL_PREFIX = $(ROOT_DIR)/build/extlib
EXTERNAL_SENTINEL_DIR = $(EXTERNAL_PREFIX)/sentinel
EXTERNAL_INSTALL_PREFIX = $(EXTERNAL_PREFIX)/install
EXTERNAL_INTERMEDIATE_PREFIX = $(EXTERNAL_PREFIX)/src

# NOTE: If you update one of these versions, you _MUST_ double check the file
# list (named <libname>_files below) used as output when building them.
#
# They're ordered based on dependency. So things that depend on other things will
# always be after them.
BZIP_VER     = bzip2-1.0.8
ZLIB_VER     = zlib-1.2.13
PNG_VER      = libpng-1.6.39
JPEG_VER     = jpeg-9f
OGG_VER      = libogg-1.3.5
VORBIS_VER   = libvorbis-1.3.7
FREETYPE_VER = freetype-2.13.0
SDL_VER      = SDL-1.2.15
SDLIMAGE_VER = SDL_image-1.2.12
SMPEG_VER    = smpeg
SDLMIXER_VER = SDL_mixer-1.2.12
SDLTTF_VER   = SDL_ttf-2.0.11


################################################################################
##-- bzip2 ---------------------------------------------------------------------
bzip_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(BZIP_VER)" -type f)
bzip_files = \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/bin/, bunzip2.exe bzcat.exe bzcmp bzdiff bzegrep bzfgrep \
		bzgrep bzip2.exe bzip2recover.exe bzless bzmore) \
	$(EXTERNAL_INSTALL_PREFIX)/include/bzlib.h \
	$(EXTERNAL_INSTALL_PREFIX)/lib/libbz2.a \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/man/man1/, bzcmp.1 bzdiff.1 bzegrep.1 bzfgrep.1 bzgrep.1 bzip2.1 bzless.1 bzmore.1) 

.PHONY: bzip_clean 
bzip_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(BZIP_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/bzip.sentinel
	rm $(bzip_files)

$(bzip_files): $(EXTERNAL_SENTINEL_DIR)/bzip.sentinel ;
internal_bzip2 = $(EXTERNAL_SENTINEL_DIR)/bzip.sentinel

$(EXTERNAL_SENTINEL_DIR)/bzip.sentinel: $(bzip_input_files)
	@echo "Building $(BZIP_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(BZIP_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(BZIP_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(BZIP_VER) && \
	$(MAKE) PREFIX="$(EXTERNAL_INSTALL_PREFIX)" $(REDSO) && \
	$(MAKE) PREFIX="$(EXTERNAL_INSTALL_PREFIX)" install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@


################################################################################
##-- zlib ----------------------------------------------------------------------
zlib_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(ZLIB_VER)" -type f)
zlib_files = \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/, zconf.h zlib.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libz.a pkgconfig/zlib.pc) \
	$(EXTERNAL_INSTALL_PREFIX)/share/man/man3/zlib.3

.PHONY: zlib_clean 
zlib_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(ZLIB_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/zlib.sentinel
	rm $(zlib_files)

$(zlib_files): $(EXTERNAL_SENTINEL_DIR)/zlib.sentinel ;
internal_z = $(EXTERNAL_SENTINEL_DIR)/zlib.sentinel

$(EXTERNAL_SENTINEL_DIR)/zlib.sentinel: $(zlib_input_files)
	@echo "Building $(ZLIB_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(ZLIB_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(ZLIB_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(ZLIB_VER) && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --static $(OTHERCONFIG) $(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@
	
################################################################################
##-- png -----------------------------------------------------------------------
libpng_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(PNG_VER)" -type f)
libpng_files = \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/bin/, libpng-config libpng16-config png-fix-itxt.exe pngfix.exe) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/libpng16/, png.h pngconf.h pnglibconf.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/, png.h pngconf.h pnglibconf.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libpng.a libpng.la libpng16.a libpng16.la) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/pkgconfig/, libpng.pc libpng16.pc) 

.PHONY: libpng_clean
libpng_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(PNG_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/libpng.sentinel
	rm $(libpng_files)

$(libpng_files): $(EXTERNAL_SENTINEL_DIR)/libpng.sentinel ;
internal_png = $(EXTERNAL_SENTINEL_DIR)/libpng.sentinel

$(EXTERNAL_SENTINEL_DIR)/libpng.sentinel: $(libpng_input_files) $(EXTERNAL_SENTINEL_DIR)/zlib.sentinel
	@echo "Building $(PNG_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(PNG_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(PNG_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(PNG_VER) && \
	autoreconf -ivf && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --disable-shared --with-zlib-prefix="$(EXTERNAL_INSTALL_PREFIX)" $(OTHERCONFIG) $(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
##-- jpeg ----------------------------------------------------------------------
libjpeg_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(JPEG_VER)" -type f)
libjpeg_files = \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/bin/, cjpeg.exe djpeg.exe jpegtran.exe rdjpgcom.exe wrjpgcom.exe) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/, jconfig.h jerror.h jmorecfg.h jpeglib.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libjpeg.a libjpeg.la) \
	$(EXTERNAL_INSTALL_PREFIX)/lib/pkgconfig/libjpeg.pc \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/share/man/man1/, cjpeg.1 djpeg.1 jpegtran.1 rdjpgcom.1 wrjpgcom.1)

.PHONY: libjpeg_clean
libjpeg_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(JPEG_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/libjpeg.sentinel
	rm $(libjpeg_files)

$(libjpeg_files): $(EXTERNAL_SENTINEL_DIR)/libjpeg.sentinel ;
internal_jpeg = $(EXTERNAL_SENTINEL_DIR)/libjpeg.sentinel

$(EXTERNAL_SENTINEL_DIR)/libjpeg.sentinel: $(libjpeg_input_files)
	@echo "Building $(JPEG_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(JPEG_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(JPEG_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(JPEG_VER) && \
	autoreconf -ivf && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --disable-shared --enable-static $(OTHERCONFIG) $(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
##-- ogg -----------------------------------------------------------------------
libogg_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(OGG_VER)" -type f)
libogg_files =  \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/ogg/, config_types.h ogg.h os_types.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libogg.a libogg.la pkgconfig/ogg.pc) \
	$(EXTERNAL_INSTALL_PREFIX)/share/aclocal/ogg.m4

.PHONY: libogg_clean
libogg_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(OGG_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/libogg.sentinel
	rm $(libogg_files)

$(libogg_files): $(EXTERNAL_SENTINEL_DIR)/libogg.sentinel ;

$(EXTERNAL_SENTINEL_DIR)/libogg.sentinel: $(libogg_input_files)
	@echo "Building $(OGG_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(OGG_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	mkdir -p $(EXTERNAL_INSTALL_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(OGG_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(OGG_VER) && \
	autoreconf -ivf && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --disable-shared $(OTHERCONFIG) $(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
##-- vorbis --------------------------------------------------------------------
libvorbis_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(VORBIS_VER)" -type f)
libvorbis_files = \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/vorbis/, codec.h vorbisenc.h vorbisfile.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libvorbis.a libvorbis.la libvorbisenc.a libvorbisenc.la libvorbisfile.a libvorbisfile.la)  \
	$(EXTERNAL_INSTALL_PREFIX)/share/aclocal/vorbis.m4 \
	
.PHONY: libvorbis_clean
libvorbis_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(VORBIS_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/libvorbis.sentinel
	rm $(libvorbis_files)

$(libvorbis_files): $(EXTERNAL_SENTINEL_DIR)/libvorbis.sentinel ;

# This implies both vorbis and, indirectly, ogg, matching prior behavior, shouls probably separate it out i nthe future.
internal_ogglibs = $(EXTERNAL_SENTINEL_DIR)/libvorbis.sentinel 

$(EXTERNAL_SENTINEL_DIR)/libvorbis.sentinel: $(EXTERNAL_SENTINEL_DIR)/libogg.sentinel $(libvorbis_input_files)
	@echo "Building $(VORBIS_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(VORBIS_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(VORBIS_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(VORBIS_VER) && \
	autoreconf -ivf && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --disable-shared --disable-docs $(OTHERCONFIG) $(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
##-- freetype2 -----------------------------------------------------------------
freetype2_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(FREETYPE_VER)" -type f)
freetype2_files = \
	$(EXTERNAL_INSTALL_PREFIX)/bin/freetype-config \
	$(EXTERNAL_INSTALL_PREFIX)/include/freetype2/ft2build.h \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/freetype2/freetype/config/, \
		ftconfig.h ftheader.h ftmodule.h ftoption.h ftstdlib.h integer-types.h mac-support.h public-macros.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/freetype2/freetype/, \
		freetype.h ftadvanc.h ftbbox.h ftbdf.h ftbitmap.h ftbzip2.h ftcache.h ftchapters.h ftcid.h ftcolor.h \
		ftdriver.h fterrdef.h fterrors.h ftfntfmt.h ftgasp.h ftglyph.h ftgxval.h ftgzip.h ftimage.h ftincrem.h \
		ftlcdfil.h ftlist.h ftlogging.h ftlzw.h ftmac.h ftmm.h ftmodapi.h ftmoderr.h ftotval.h ftoutln.h ftparams.h \
		ftpfr.h ftrender.h ftsizes.h ftsnames.h ftstroke.h ftsynth.h ftsystem.h fttrigon.h fttypes.h ftwinfnt.h \
		otsvg.h t1tables.h ttnameid.h tttables.h tttags.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libfreetype.a libfreetype.la) \
	$(EXTERNAL_INSTALL_PREFIX)/lib/pkgconfig/freetype2.pc \
	$(EXTERNAL_INSTALL_PREFIX)/share/aclocal/freetype2.m4 \
	$(EXTERNAL_INSTALL_PREFIX)/share/man/man1/freetype-config.1

.PHONY: freetype2_clean
freetype2_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(FREETYPE_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/freetype2.sentinel
	rm $(freetype2_files)

$(freetype2_files): $(EXTERNAL_SENTINEL_DIR)/freetype2.sentinel ;
internal_freetype = $(EXTERNAL_SENTINEL_DIR)/freetype2.sentinel

$(EXTERNAL_SENTINEL_DIR)/freetype2.sentinel: $(freetype2_input_files)
	@echo "Building $(FREETYPE_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(FREETYPE_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(FREETYPE_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(FREETYPE_VER) && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --enable-freetype-config --disable-shared --enable-static --without-harfbuzz --without-brotli $(OTHERCONFIG) $(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
##-- SDL -----------------------------------------------------------------------
libsdl_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(SDL_VER)" -type f)
libsdl_files = \
	$(EXTERNAL_INSTALL_PREFIX)/bin/sdl-config \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/SDL/, \
		begin_code.h close_code.h SDL.h SDL_active.h SDL_audio.h SDL_byteorder.h SDL_cdrom.h SDL_config.h SDL_cpuinfo.h \
		SDL_endian.h SDL_error.h SDL_events.h SDL_getenv.h SDL_joystick.h SDL_keyboard.h SDL_keysym.h SDL_loadso.h \
		SDL_main.h SDL_mouse.h SDL_mutex.h SDL_name.h SDL_opengl.h SDL_platform.h SDL_quit.h SDL_rwops.h SDL_stdinc.h \
		SDL_syswm.h SDL_thread.h SDL_timer.h SDL_types.h SDL_version.h SDL_video.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libSDL.a libSDL.la libSDLmain.a libSDLmain.la) \
	$(EXTERNAL_INSTALL_PREFIX)/lib/pkgconfig/sdl.pc \
	$(EXTERNAL_INSTALL_PREFIX)/share/aclocal/sdl.m4

.PHONY: libsdl_clean
libsdl_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDL_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel
	rm $(libsdl_files)

$(libsdl_files): $(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel ;
internal_sdl = $(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel

$(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel: $(libsdl_input_files) $(if $(INTERNAL_LIBPNG), $(EXTERNAL_SENTINEL_DIR)/libpng.sentinel)
	@echo "Building $(SDL_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDL_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(SDL_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDL_VER) && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" $(SDLOTHERCONFIG) \
		--disable-shared \
		--disable-joystick \
		--disable-nas \
		--disable-video-fbcon \
		--disable-video-directfb \
		--disable-video-svga \
		--disable-video-vgl \
		--disable-video-wscons \
		--disable-video-opengl \
		$(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@
	
################################################################################
##-- SDL_image -----------------------------------------------------------------
libsdlimage_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(SDLIMAGE_VER)" -type f)
libsdlimage_files = \
	$(EXTERNAL_INSTALL_PREFIX)/include/SDL/SDL_image.h \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libSDL_image.a libSDL_image.la) \
	$(EXTERNAL_INSTALL_PREFIX)/lib/pkgconfig/SDL_image.pc

.PHONY: libsdlimage_clean
libsdlimage_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLIMAGE_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/libsdlimage.sentinel
	rm -f $(libsdlimage_files)

$(libsdlimage_files): $(EXTERNAL_SENTINEL_DIR)/libsdlimage.sentinel ;
internal_sdl_image = $(EXTERNAL_SENTINEL_DIR)/libsdlimage.sentinel

$(EXTERNAL_SENTINEL_DIR)/libsdlimage.sentinel: \
		$(libsdlimage_input_files) \
		$(if $(INTERNAL_SDL), $(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel) \
		$(if $(INTERNAL_LIBPNG), $(EXTERNAL_SENTINEL_DIR)/libpng.sentinel) \
		$(if $(INTERNAL_LIBJPEG), $(EXTERNAL_SENTINEL_DIR)/libjpeg.sentinel)
	@echo "Building $(SDLIMAGE_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLIMAGE_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(SDLIMAGE_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLIMAGE_VER) && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" $(OTHERCONFIG) \
		--disable-shared \
		--disable-lbm \
		--disable-pcx \
		--disable-pnm \
		--disable-tga \
		--disable-xcf \
		--disable-xv \
		--disable-tif \
		--disable-webp \
		--disable-png-shared \
		--disable-jpg-shared \
		CPPFLAGS="-I$(EXTERNAL_INSTALL_PREFIX)/include" \
		LDFLAGS="-L$(EXTERNAL_INSTALL_PREFIX)/lib" \
		LIBS="$(if $(INTERNAL_SDL), $(shell export PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) && $(SDL_CONFIG) --static-libs), $(SDL_CONFIG) --static-libs)" \
		CFLAGS="-Wno-error=incompatible-pointer-types" \
		$(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
##-- smpeg ---------------------------------------------------------------------
smpeg_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(SMPEG_VER)" -type f)
smpeg_files = \
	$(EXTERNAL_INSTALL_PREFIX)/bin/smpeg-config \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/include/smpeg/, \
		MPEG.h MPEGaction.h MPEGaudio.h MPEGerror.h MPEGfilter.h MPEGlist.h MPEGring.h \
		MPEGstream.h MPEGsystem.h MPEGvideo.h smpeg.h) \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libsmpeg.a libsmpeg.la) \
	$(EXTERNAL_INSTALL_PREFIX)/share/aclocal/smpeg.m4

.PHONY: smpeg_clean
smpeg_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SMPEG_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/smpeg.sentinel
	rm $(smpeg_files)

$(smpeg_files): $(EXTERNAL_SENTINEL_DIR)/smpeg.sentinel ;
internal_smpeg = $(EXTERNAL_SENTINEL_DIR)/smpeg.sentinel

ifdef DEBUG
	SMPEG_DEBUG=--enable-debug
endif

$(EXTERNAL_SENTINEL_DIR)/smpeg.sentinel: $(smpeg_input_files) $(if $(INTERNAL_SDL), $(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel)
	@echo "Building $(SMPEG_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SMPEG_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(SMPEG_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SMPEG_VER) && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --disable-shared --enable-static $(SMPEG_DEBUG) $(OTHERCONFIG) \
		--disable-gtk-player --disable-opengl-player $(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
#-- SDL_mixer -----------------------------------------------------------------
libsdlmixer_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(SDLMIXER_VER)" -type f)
libsdlmixer_files = \
	$(EXTERNAL_INSTALL_PREFIX)/include/SDL/SDL_mixer.h \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libSDL_mixer.a libSDL_mixer.la) \
	$(EXTERNAL_INSTALL_PREFIX)/lib/pkgconfig/SDL_mixer.pc

.PHONY: libsdlmixer_clean
libsdlmixer_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLMIXER_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/libsdlmixer.sentinel
	rm $(libsdlmixer_files)

$(libsdlmixer_files): $(EXTERNAL_SENTINEL_DIR)/libsdlmixer.sentinel ;
internal_sdl_mixer = $(EXTERNAL_SENTINEL_DIR)/libsdlmixer.sentinel

$(EXTERNAL_SENTINEL_DIR)/libsdlmixer.sentinel: \
		$(libsdlmixer_input_files) \
		$(if $(INTERNAL_SDL), $(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel) \
		$(if $(INTERNAL_SDL), $(EXTERNAL_SENTINEL_DIR)/libogg.sentinel $(EXTERNAL_SENTINEL_DIR)/libvorbis.sentinel) \
		$(if $(INTERNAL_SMPEG), $(EXTERNAL_SENTINEL_DIR)/smpeg.sentinel)
	@echo "Building $(SDLMIXER_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLMIXER_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(SDLMIXER_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLMIXER_VER) && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --disable-shared --disable-music-cmd --disable-music-timidity-midi $(OTHERCONFIG) \
		CPPFLAGS="-I$(EXTERNAL_INSTALL_PREFIX)/include" \
		CFLAGS="$(CFLAGS) -Wno-error=implicit-function-declaration" \
		LDFLAGS="-L$(EXTERNAL_INSTALL_PREFIX)/lib" \
		LIBS="$(if $(INTERNAL_SDL), $(shell export PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) && $(SDL_CONFIG) --static-libs), $(SDL_CONFIG) --static-libs) \
			$(if $(INTERNAL_SMPEG), $(shell export PKG_CONFIG_PATH=\$(PKG_CONFIG_PATH) && $(SMPEG_CONFIG) --static-libs), $(SMPEG_CONFIG) --static-libs))" \
		$(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
##-- SDL_ttf -------------------------------------------------------------------
libsdlttf_input_files = $(shell find "$(EXTERNAL_SOURCE)/$(SDLTTF_VER)" -type f)
libsdlttf_files = \
	$(EXTERNAL_INSTALL_PREFIX)/include/SDL/SDL_ttf.h \
	$(addprefix $(EXTERNAL_INSTALL_PREFIX)/lib/, libSDL_ttf.a libSDL_ttf.la) \
	$(EXTERNAL_INSTALL_PREFIX)/lib/pkgconfig/SDL_ttf.pc

.PHONY: libsdlttf_clean
libsdlttf_clean:
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLTTF_VER)
	rm -f $(EXTERNAL_SENTINEL_DIR)/libsdlttf.sentinel
	rm $(libsdlttf_files)

$(libsdlttf_files): $(EXTERNAL_SENTINEL_DIR)/libsdlttf.sentinel ;
internal_sdl_ttf = $(EXTERNAL_SENTINEL_DIR)/libsdlttf.sentinel

$(EXTERNAL_SENTINEL_DIR)/libsdlttf.sentinel: \
		$(libsdlttf_input_files) \
		$(if $(INTERNAL_SDL), $(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel) \
		$(if $(INTERNAL_FREETYPE), $(EXTERNAL_SENTINEL_DIR)/freetype2.sentinel)
	@echo "Building $(SDLTTF_VER)"
	rm -rf $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLTTF_VER)
	mkdir -p $(EXTERNAL_INTERMEDIATE_PREFIX)
	cp -r $(EXTERNAL_SOURCE)/$(SDLTTF_VER) $(EXTERNAL_INTERMEDIATE_PREFIX)
	cd $(EXTERNAL_INTERMEDIATE_PREFIX)/$(SDLTTF_VER) && \
	./configure --prefix="$(EXTERNAL_INSTALL_PREFIX)" --disable-shared $(OTHERCONFIG) \
		--with-freetype-exec-prefix="$(EXTERNAL_INSTALL_PREFIX)" \
		CPPFLAGS="-I$(EXTERNAL_INSTALL_PREFIX)/include" \
		LDFLAGS="-L$(EXTERNAL_INSTALL_PREFIX)/lib" \
		LIBS="$(if $(INTERNAL_SDL), $(shell export PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) && $(SDL_CONFIG) --static-libs), $(SDL_CONFIG) --static-libs) \
			$(if $(INTERNAL_FREETYPE), $(shell export PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) && $(FREETYPE_CONFIG) --libs), $(FREETYPE_CONFIG) --libs)" \
		$(REDIR) && \
	$(MAKE) $(REDSO) && \
	$(MAKE) install $(REDSO) && \
	mkdir -p $(EXTERNAL_SENTINEL_DIR) && \
	touch $@

################################################################################
##-- extlib --------------------------------------------------------------------
extlib: \
		$(EXTERNAL_SENTINEL_DIR)/bzip.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/zlib.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/libogg.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/libvorbis.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/libpng.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/libjpeg.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/freetype2.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/libsdlimage.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/libsdlmixer.sentinel \
		$(EXTERNAL_SENTINEL_DIR)/libsdlttf.sentinel
	echo "Extlibs built"

.PHONY: extlib_clean
extlib_clean:
	rm -rf $(EXTERNAL_PREFIX)
	rm extlib.sentinel

INTERNALLY_BUILT_LIBS = \
	$(zlib_files) \
	$(if $(INTERNAL_BZIP2), $(EXTERNAL_SENTINEL_DIR)/bzip.sentinel) \
	$(if $(INTERNAL_LIBPNG), $(EXTERNAL_SENTINEL_DIR)/libpng.sentinel) \
	$(if $(INTERNAL_LIBJPEG), $(EXTERNAL_SENTINEL_DIR)/libjpeg.sentinel) \
	$(if $(INTERNAL_FREETYPE), $(EXTERNAL_SENTINEL_DIR)/freetype2.sentinel) \
	$(if $(INTERNAL_OGGLIBS), $(EXTERNAL_SENTINEL_DIR)/libogg.sentinel $(EXTERNAL_SENTINEL_DIR)/libvorbis.sentinel) \
	$(if $(INTERNAL_SDL), $(EXTERNAL_SENTINEL_DIR)/libsdl.sentinel) \
	$(if $(INTERNAL_SDL_IMAGE), $(EXTERNAL_SENTINEL_DIR)/libsdlimage.sentinel) \
	$(if $(INTERNAL_SMPEG), $(EXTERNAL_SENTINEL_DIR)/smpeg.sentinel) \
	$(if $(INTERNAL_SDL_MIXER), $(EXTERNAL_SENTINEL_DIR)/libsdlmixer.sentinel) \
	$(if $(INTERNAL_SDL_TTF), $(EXTERNAL_SENTINEL_DIR)/libsdlttf.sentinel)
