if(VCPKG_TARGET_TRIPLET STREQUAL arm64-android)
    set(ANDROID_ABI arm64-v8a)
    set(CMAKE_ANDROID_ARCH_ABI arm64-v8a)
elseif(VCPKG_TARGET_TRIPLET STREQUAL arm-android)
    set(ANDROID_ABI armeabi-v7a)
    set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
elseif(VCPKG_TARGET_TRIPLET STREQUAL arm-neon-android)
    set(ANDROID_ABI armeabi-v7a)
    set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
elseif(VCPKG_TARGET_TRIPLET STREQUAL x64-android)
    set(ANDROID_ABI x86_64)
    set(CMAKE_ANDROID_ARCH_ABI x86_64)
elseif(VCPKG_TARGET_TRIPLET STREQUAL x86-android)
    set(ANDROID_ABI x86)
    set(CMAKE_ANDROID_ARCH_ABI x86)
elseif(VCPKG_TARGET_TRIPLET STREQUAL armv6-android)
    set(ANDROID_ABI armeabi)
    set(CMAKE_ANDROID_ARCH_ABI armeabi-v6)
endif()
