name: build

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install dependencies (Linux)
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe"
        sudo apt-get update -y -qq
        sudo apt-get install libasound2-dev libpulse-dev libwebp-dev libxrandr-dev tar autoconf libtool clang
    - name: configure
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cpp_compiler }}
      run: |
        ./configure --with-internal-libs
    - name: build dependencies
      run: |
        NCPUS=$(getconf _NPROCESSORS_ONLN)
        make -j $NCPUS VERBOSE=true extlib
    - name: build
      run: |
        NCPUS=$(getconf _NPROCESSORS_ONLN)
        make -j $NCPUS VERBOSE=true
        make -j $NCPUS VERBOSE=true tools
        make check
        tar -czvf onscripter-en.Linux.${{ matrix.c_compiler }}.x86-64.tar.gz \
          onscripter-en \
          README.md \
          COPYING \
          CHANGES \
          build/tools/ns2conv \
          build/tools/nsaconv \
          build/tools/sardec \
          build/tools/batchconv \
          build/tools/nbzdec \
          build/tools/ns2make \
          build/tools/nsamake \
          build/tools/sarconv \
          build/tools/ns2dec \
          build/tools/nsadec \
          build/tools/nscdec \
          build/tools/nscmake \
          build/tools/sarmake

    - uses: actions/upload-artifact@v4
      with:
        name: ONScripter-EN Linux x86-64 ${{ matrix.c_compiler }} Build
        path: ${{ github.workspace }}/onscripter-en.Linux.${{ matrix.c_compiler }}.x86-64.tar.gz

  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            cc: gcc
            sys: mingw64
            env: x86_64
            arch: x86-64
          - os: windows-latest
            cc: gcc
            sys: mingw32
            env: i686
            arch: i686
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install:
          mingw-w64-${{matrix.env}}-SDL
          mingw-w64-${{matrix.env}}-SDL_ttf
          mingw-w64-${{matrix.env}}-SDL_image
          mingw-w64-${{matrix.env}}-bzip2
          mingw-w64-${{matrix.env}}-libmikmod
          mingw-w64-${{matrix.env}}-libmad
          mingw-w64-${{matrix.env}}-libogg
          mingw-w64-${{matrix.env}}-libvorbis
          mingw-w64-${{matrix.env}}-freetype
          mingw-w64-${{matrix.env}}-iconv
          mingw-w64-${{matrix.env}}-zlib
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-autotools
          mingw-w64-${{matrix.env}}-flac
          mingw-w64-${{matrix.env}}-autotools
          mingw-w64-${{matrix.env}}-libtool
          make
          zip
    - name: configure
      run: |
        ./configure --with-internal-libs
    - name: build dependencies
      run: |
        NCPUS=$(getconf _NPROCESSORS_ONLN)
        make -j $NCPUS VERBOSE=true extlib
    - shell: msys2 {0}
      name: build
      run: |
        NCPUS=$(getconf _NPROCESSORS_ONLN)
        make -j $NCPUS VERBOSE=true
        make -j $NCPUS VERBOSE=true tools
        make check
        zip onscripter-en.Windows.${{matrix.arch}}.zip \
          onscripter-en.exe \
          README.md \
          COPYING \
          CHANGES \
          build/tools/ns2conv.exe \
          build/tools/nsaconv.exe \
          build/tools/sardec.exe \
          build/tools/batchconv.exe \
          build/tools/nbzdec.exe \
          build/tools/ns2make.exe \
          build/tools/nsamake.exe \
          build/tools/sarconv.exe \
          build/tools/ns2dec.exe \
          build/tools/nsadec.exe \
          build/tools/nscdec.exe \
          build/tools/nscmake.exe \
          build/tools/sarmake.exe

    - uses: actions/upload-artifact@v4
      with:
        name: ONScripter-EN Windows ${{matrix.arch}} Build
        path: ${{ github.workspace }}/onscripter-en.Windows.${{matrix.arch}}.zip
